spring.application.name=BookingService
spring.datasource.url=jdbc:postgresql://localhost:5432/Spring?currentSchema=stellar
spring.datasource.username=postgres
spring.datasource.password=root
server.port=8032
# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Additional properties
spring.datasource.driver-class-name=org.postgresql.Driver
# Eureka client configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Springdoc OpenAPI configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-custom.html

#spring.config.import = configserver:http://localhost:8088
